version: "3.7"

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3030:3030
    volumes:
      - ./todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db_test


 
